import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { mkdirSync, copyFileSync } from "node:fs";
import sveltePlugin from "esbuild-svelte";

// Copy the compiled plugin bundle plus its metadata/style files into dist/.
// Runs on every build (watch and production) via the plugin's onEnd hook.
function copyToDist() {
  const outDir = "dist";
  mkdirSync(outDir, { recursive: true });
  copyFileSync("main.js", `${outDir}/main.js`);
  copyFileSync("manifest.json", `${outDir}/manifest.json`);
  copyFileSync("styles.css", `${outDir}/styles.css`);
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
Source: https://github.com/nightfall-yl/obsidian-attend-dashboard
*/
`;

const prod = process.argv[2] === "production";
const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "obsidian-dataview",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules
  ],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  loader: {
    ".css": "text",
  },
  plugins: [
    sveltePlugin({
      compilerOptions: {
        css: true,
      },
    }),
    {
      name: "copy-to-dist",
      setup(build) {
        build.onEnd(() => {
          copyToDist();
        });
      },
    },
  ],
  mainFields: ["svelte", "browser", "module", "main"],
});

if (prod) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
